[build]
  # Directory to change to before starting a build
  base = "."
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"
  # Default build command
  command = "npm run build:client"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  # API calls will use Netlify Functions
  VITE_API_URL = ""
  # MongoDB connection for Netlify Functions
  MONGODB_URI = "mongodb+srv://rehansaqib:Cusit%4012926@cluster0.koi0z.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  NODE_ENV = "production"

# Redirect rules for client-side routing
# API redirects - Using Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Form handling (if needed)
# [[redirects]]
#   from = "/contact"
#   to = "/contact-success"
#   status = 200
#   conditions = {Role = ["admin"]}

# Environment-specific settings
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"